set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK] 
    
set_property PACKAGE_PIN W7 [get_ports {HEX_OUT[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[0]}]
set_property PACKAGE_PIN W6 [get_ports {HEX_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[1]}]
set_property PACKAGE_PIN U8 [get_ports {HEX_OUT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[2]}]
set_property PACKAGE_PIN V8 [get_ports {HEX_OUT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[3]}]
set_property PACKAGE_PIN U5 [get_ports {HEX_OUT[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[4]}]
set_property PACKAGE_PIN V5 [get_ports {HEX_OUT[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[5]}]
set_property PACKAGE_PIN U7 [get_ports {HEX_OUT[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[6]}]
set_property PACKAGE_PIN V7 [get_ports {HEX_OUT[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[7]}]
 
set_property PACKAGE_PIN U2 [get_ports {SEG_SELECT_OUT[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[0]}]   
set_property PACKAGE_PIN U4 [get_ports {SEG_SELECT_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[1]}]
set_property PACKAGE_PIN V4 [get_ports {SEG_SELECT_OUT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[2]}]
set_property PACKAGE_PIN W4 [get_ports {SEG_SELECT_OUT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[3]}]
    
        
set_property PACKAGE_PIN U18 [get_ports RESET]
    set_property IOSTANDARD LVCMOS33 [get_ports RESET]    
set_property PACKAGE_PIN A14 [get_ports Pump_Outer_Control]
    set_property IOSTANDARD LVCMOS33 [get_ports Pump_Outer_Control]    
set_property PACKAGE_PIN A16 [get_ports Valve_Inner_Control]
    set_property IOSTANDARD LVCMOS33 [get_ports Valve_Inner_Control] 
set_property PACKAGE_PIN B15 [get_ports Pump_Inner_Control]
    set_property IOSTANDARD LVCMOS33 [get_ports Pump_Inner_Control]   
set_property PACKAGE_PIN B16 [get_ports Value_Outer_Control]
    set_property IOSTANDARD LVCMOS33 [get_ports Value_Outer_Control]    
    
set_property PACKAGE_PIN J3 [get_ports {vauxp6}]				
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxp6}]
set_property PACKAGE_PIN K3 [get_ports {vauxn6}]				
    set_property IOSTANDARD LVCMOS33 [get_ports {vauxn6}]  
    
set_property PACKAGE_PIN U16 [get_ports Pump_Outer_Control_LED]
    set_property IOSTANDARD LVCMOS33 [get_ports Pump_Outer_Control_LED]   
set_property PACKAGE_PIN E19 [get_ports Pump_Inner_Control_LED]
    set_property IOSTANDARD LVCMOS33 [get_ports Pump_Inner_Control_LED]   
set_property PACKAGE_PIN L1 [get_ports Value_Outer_Control_LED]
    set_property IOSTANDARD LVCMOS33 [get_ports Value_Outer_Control_LED]   
  set_property PACKAGE_PIN P1 [get_ports Valve_Inner_Control_LED]
    set_property IOSTANDARD LVCMOS33 [get_ports Valve_Inner_Control_LED] 
    
#set_property PACKAGE_PIN W18 [get_ports LED[0]]
#    set_property IOSTANDARD LVCMOS33 [get_ports LED[0]] 
#set_property PACKAGE_PIN U15 [get_ports LED[1]]
#    set_property IOSTANDARD LVCMOS33 [get_ports LED[1]] 
#set_property PACKAGE_PIN U14 [get_ports LED[2]]
#    set_property IOSTANDARD LVCMOS33 [get_ports LED[2]] 
#set_property PACKAGE_PIN V14 [get_ports LED[3]]
#    set_property IOSTANDARD LVCMOS33 [get_ports LED[3]] 
#set_property PACKAGE_PIN V13 [get_ports LED[4]]
#    set_property IOSTANDARD LVCMOS33 [get_ports LED[4]] 
#set_property PACKAGE_PIN V3 [get_ports LED[5]]
#    set_property IOSTANDARD LVCMOS33 [get_ports LED[5]] 
#set_property PACKAGE_PIN W3 [get_ports LED[6]]
#    set_property IOSTANDARD LVCMOS33 [get_ports LED[6]] 
#set_property PACKAGE_PIN U3 [get_ports LED[7]]
#    set_property IOSTANDARD LVCMOS33 [get_ports LED[7]] 
    
set_property PACKAGE_PIN P3 [get_ports Full_state]
    set_property IOSTANDARD LVCMOS33 [get_ports Full_state] 
set_property PACKAGE_PIN N3 [get_ports Empty_state]
    set_property IOSTANDARD LVCMOS33 [get_ports Empty_state] 
    
set_property PACKAGE_PIN B18 [get_ports rx]
    set_property IOSTANDARD LVCMOS33 [get_ports rx]         
set_property PACKAGE_PIN A18 [get_ports tx]
    set_property IOSTANDARD LVCMOS33 [get_ports tx] 